python src/main.py \
    --seed=0 \
    --mode="train" \
    --data_dir="data" \
    --train_prefix="train" \
    --valid_prefix="test" \
    --model_type="gpt2-medium" \
    --bos_token="<bos>" \
    --sp1_token="<sp1>" \
    --sp2_token="<sp2>" \
    --gpu="0" \
    --lr=1e-5 \
    --warmup_ratio=0.0 \
    --batch_size=8 \
    --num_workers=0 \
    --num_epochs=100 \
    --max_len=1024 \
    --layers=0